Merge with origin/osx

diff --git a/plugins/ledcor/mcs-pack b/plugins/ledcor/mcs-pack
--- a/plugins/ledcor/mcs-pack
+++ b/plugins/ledcor/mcs-pack
@@ -3,6 +3,9 @@
 # requires the jq command line tool
 # https://stedolan.github.io/jq/
 
+scriptdir=$0:A
+scriptdir=${scriptdir%/*}
+
 MCSAPIDIR="${MCSAPIDIR:-$(echo ~"/MCS APIs")}"
 [[ -d $MCSAPIDIR ]] || mkdir -p "$MCSAPIDIR"
 
@@ -10,6 +13,23 @@ source ~/.nvm/nvm.sh
 
 () {
   # TODO: make sure to go to the nearest folder with package.json
+
+  # validate the package.json
+  < package.json jq . > /dev/null || exit
+
+  # ensure that the appropriate config files are available
+  local configFilesRaw configFiles missingConfigFile
+  configFilesRaw="$(< package.json jq -r '.configFiles[]')"
+  configFiles=("${(f)configFilesRaw}")
+  missingConfigFile=false
+  for f in $configFiles ; do
+    if [[ ! -f $f ]] ; then
+      echo "missing $f"
+      missingConfigFile=true
+    fi
+  done
+  if $missingConfigFile ; then return 1; fi
+
   # TODO: support a .mcsignore file
 
   local filename
@@ -17,15 +37,17 @@ source ~/.nvm/nvm.sh
 
   [[ -d node_modules ]] && mv node_modules .dev_node_modules
   nvm use v0.10.25 || return 1
-  npm i --production || return 1
   if [[ -e npm-shrinkwrap.json ]]; then env rm npm-shrinkwrap.json || return 1; fi
-  npm shrinkwrap || return 1
+  npm i --production --node-gyp=true || return 1
+  npm dedupe
+  (( $(< package.json jq '.dependencies|length') == 0 )) || npm shrinkwrap || return 1
 
   [[ -e "$filename" ]] && trash "$filename"
 
   local dir
   dir="$(basename $PWD)"
 
+  # TODO: use npm pack + convert it to zip + configFiles to zip
   (cd ..
     typeset -a files
     files=( $dir/**/*(.) )
