update

diff --git a/plugins/ledcor/mcs-pack b/plugins/ledcor/mcs-pack
--- a/plugins/ledcor/mcs-pack
+++ b/plugins/ledcor/mcs-pack
@@ -11,7 +11,6 @@ source ~/.nvm/nvm.sh
 () {
   # TODO: make sure to go to the nearest folder with package.json
   # TODO: support a .mcsignore file
-  # TODO: support automatically uploading
 
   local filename
   filename="$MCSAPIDIR/$(jq -r .name package.json)-$(jq -r .version package.json | sed 's/\./_/g').zip"
@@ -30,8 +29,21 @@ source ~/.nvm/nvm.sh
   (cd ..
     typeset -a files
     files=( $dir/**/*(.) )
+    if [[ -e $dir/.env ]] ; then
+      files=( $dir/.env $dir/.env.example $files )
+    elif [[ -e $dir/.env.example ]] ; then
+      echo ".env file missing!"
+      return 1
+    fi
     echo ${(F)files} | zip "$filename" -@ || return 1
   ) || return 1
+
+  echo "Wrote file to $filename"
+
+  if [[ $1 == '-u' ]] ; then
+    apiid="$(jq .mcsDeploy.dev.id package.json -r -e)"
+    (( $? == 0 )) && (nvm use 6 && node "$scriptdir/upload-impl.nightmare.js" "$apiid" "$filename") || "not uploading, mcsDeploy.dev.id not in package.json"
+  fi
 
   if [[ -d node_modules ]] ; then env rm -r node_modules || return 1; fi
   [[ -d .dev_node_modules ]] && mv .dev_node_modules node_modules
